var logger;
try{
    console.log("BroadcastChannel is available in service Worker");
    const channel = new BroadcastChannel('sw-messages');
    logger = function(m){channel.postMessage(m)};
} catch {
    console.log("BroadcastChannel not available");
    logger = function(m){console.log(m)};
}

var cacheName = "japdict";

var urlsToCache = [
            "/",
            "/index.html",
            "/js/main.js",
            "/js/worker.js",
            "/js/nameDictWorkerLoader.js",
            "/js/dictWorkerLoader.js",
            "/js/kanjiDictWorkerLoader.js",
            "/favicon.ico",
            "/manifest.json",
            "/data/dict00.dat",
            "/data/dict01.dat",
            "/data/dict02.dat",
            "/data/dict03.dat",
            "/data/dict04.dat",
            "/data/dict05.dat",
            "/data/dict06.dat",
            "/data/dict07.dat",
            "/data/dict08.dat",
            "/data/dict09.dat",
            "/data/dict10.dat",
            "/data/dict11.dat",
            "/data/dict12.dat",
            "/data/dict13.dat",
            "/data/dict14.dat",
            "/data/dict15.dat",
            "/data/dict16.dat",
            "/data/dict17.dat",
            "/data/dict18.dat",
            "/data/dict19.dat",
            "/data/dict20.dat",
            "/data/dict21.dat",
            "/data/dict22.dat",
            "/data/dict23.dat",
            "/data/dict24.dat",
            "/data/dict25.dat",
            "/data/dict26.dat",
            "/data/dict27.dat",
            "/data/dict28.dat",
            "/data/dict29.dat",
            "/data/dict30.dat",
            "/data/dict31.dat",
            "/data/dict32.dat",
            "/data/dict33.dat",
            "/data/dict34.dat",
            "/data/dict35.dat",
            "/data/dict36.dat",
            "/data/dict37.dat",
            "/data/dict38.dat",
            "/data/dict39.dat",
            "/data/dict40.dat",
            "/data/dict41.dat",
            "/data/dict42.dat",
            "/data/dict43.dat",
            "/data/dict44.dat",
            "/data/dict45.dat",
            "/data/dict46.dat",
            "/data/dict47.dat",
            "/data/dict48.dat",
            "/data/dict49.dat",
            "/data/dict50.dat",
            "/data/dict51.dat",
            "/data/dict52.dat",
            "/data/dict53.dat",
            "/data/dict54.dat",
            "/data/dict55.dat",
            "/data/dict56.dat",
            "/data/dict57.dat",
            "/data/dict58.dat",
            "/data/dict59.dat",
            "/data/kanji00.dat",
            "/data/kanji01.dat",
            "/data/kanji02.dat",
            "/data/kanji03.dat",
            "/data/kanji04.dat",
            "/data/kanji05.dat",
            "/data/kanji06.dat",
            "/data/kanji07.dat",
            "/data/kanji08.dat",
            "/data/kanji09.dat",
            "/data/kanji10.dat",
            "/data/kanji11.dat",
            "/data/kanji12.dat",
            "/data/kanji13.dat",
            "/data/kanji14.dat",
            "/data/kanji15.dat",
            "/data/kanji16.dat",
            "/data/kanji17.dat",
            "/data/kanji18.dat",
            "/data/kanji19.dat",
            "/data/kanji20.dat",
            "/data/kanji21.dat",
            "/data/kanji22.dat",
            "/data/kanji23.dat",
            "/data/kanji24.dat",
            "/data/kanji25.dat",
            "/data/kanji26.dat",
            "/data/kanji27.dat",
            "/data/kanji28.dat",
            "/data/kanji29.dat",
            "/data/names00.dat",
            "/data/names01.dat",
            "/data/names02.dat",
            "/data/names03.dat",
            "/data/names04.dat",
            "/data/names05.dat",
            "/data/names06.dat",
            "/data/names07.dat",
            "/data/names08.dat",
            "/data/names09.dat",
            "/data/names10.dat",
            "/data/names11.dat",
            "/data/names12.dat",
            "/data/names13.dat",
            "/data/names14.dat",
            "/data/names15.dat",
            "/data/names16.dat",
            "/data/names17.dat",
            "/data/names18.dat",
            "/data/names19.dat",
            "/data/names20.dat",
            "/data/names21.dat",
            "/data/names22.dat",
            "/data/names23.dat",
            "/data/names24.dat",
            "/data/names25.dat",
            "/data/names26.dat",
            "/data/names27.dat",
            "/data/names28.dat",
            "/data/names29.dat",
            "/data/names30.dat",
            "/data/names31.dat",
            "/data/names32.dat",
            "/data/names33.dat",
            "/data/names34.dat",
            "/data/names35.dat",
            "/data/names36.dat",
            "/data/names37.dat",
            "/data/names38.dat",
            "/data/names39.dat",
            "/data/names40.dat",
            "/data/names41.dat",
            "/data/names42.dat",
            "/data/names43.dat",
            "/data/names44.dat",
            "/data/names45.dat",
            "/data/names46.dat",
            "/data/names47.dat",
            "/data/names48.dat",
            "/data/names49.dat",
            "/data/names50.dat",
            "/data/names51.dat",
            "/data/names52.dat",
            "/data/names53.dat",
            "/data/names54.dat",
            "/data/names55.dat",
            "/data/names56.dat",
            "/data/names57.dat",
            "/data/names58.dat",
            "/data/names59.dat"
        ];


addEventListener("install", function (event) {
    event.waitUntil(caches.open(cacheName)
        .then(function (cache) {
            logger('[install] Caches opened, adding all core components');
            return cache.addAll(urlsToCache);
        })
        .then(function() {
            logger('[install] All required resources have been cached');
            return self.skipWaiting();
        })
    )
})

addEventListener("fetch", function (event) {
    logger('Service Worker Intercept: ' + event.request.url);
    event.respondWith(caches.match(event.request).then(function (response) {
        return response || fetch(event.request);
    }))
})